---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lustre-pv
spec:
  capacity:
    storage: 31Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: lustre.csi.oraclecloud.com
    volumeHandle: "10.30.1.192@tcp:/lustrefs"
    fsType: lustre
    volumeAttributes:
      setupLnet: "true"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: oci.oraclecloud.com/lustre-client-configured
          operator: In
          values:
          - "true"